### ISSUE TITLE
CNTK Language Understanding doesn't create output file

### ISSUE THREAD

**Issue by dan1-ru** [singnet/nlp-services#55]
##### **Brief description**

I try to call "Text Understanding" service with standard data (from User's guide) and get correct response, but output file is doesn't exists.

And also I can see all files in output directory: 
http://54.203.198.53:7000/LanguageUnderstanding/CNTK/Output/

Also I try to run this service with method "Intent" (after that response) and it seems the server thought for a long time.

##### **Output logs**

Status    : Ok
Model URL : http://54.203.198.53:7000/LanguageUnderstanding/CNTK/Output/b0572791d0291a980483.model
Output URL: http://54.203.198.53:7000/LanguageUnderstanding/CNTK/Output/b0572791d0291a980483.txt

Both URL's are 404.

##### **How to reproduce the error**

URL: https://beta.singularitynet.io/
Service: "Text Understanding"
Method Name: "slot_tagging"
Train CTF (URL): 
https://github.com/Microsoft/CNTK/blob/release/2.6/Tutorials/SLUHandsOn/atis.train.ctf?raw=true
Test CTF (URL): 
https://github.com/Microsoft/CNTK/blob/release/2.6/Tutorials/SLUHandsOn/atis.test.ctf?raw=true
Query List (URL): 
https://github.com/Microsoft/CNTK/blob/release/2.6/Examples/LanguageUnderstanding/ATIS/BrainScript/query.wl?raw=true
Slots List (URL): 
https://github.com/Microsoft/CNTK/blob/release/2.6/Examples/LanguageUnderstanding/ATIS/BrainScript/slots.wl?raw=true
Intent List (URL): 
https://github.com/Microsoft/CNTK/blob/release/2.6/Examples/LanguageUnderstanding/ATIS/BrainScript/intent.wl?raw=true
Vocabulary Size: 
943
Number of Labels: 
129
Number of Intents: 
26
Sentences (URL): 
http://54.203.198.53:7000/LanguageUnderstanding/CNTK/Example/sentences.txt

"Invoke"

##### **Suggest a Fix**

Hide files in output add some index file. And make the validation of input params. 

##### **Version(s)**

Beta on main ethereum network.

##### **Browsers and Operating System**

Ubuntu 16.04 / Chromium

**Comment by arturgontijo** [comment]
Hi @dan1-ru, thanks for pointing this out!
I'll investigate it and came back with a fix (following your suggestion).

**Comment by dan1-ru** [comment]
Thank you!

**Comment by dan1-ru** [comment]
Issue out of date.
